include: "rules/common.smk"


##### Target rules #####


rule all:
    input:
        expand("results/spades/{sample}/contigs.fasta", sample=samples.index),
        # "results/filtered/all.snvs.selected.vcf.gz",
        # "results/msa/snvs.fasta",
        # "results/phylogeny/fasttree-snvs.nwk",
        # "results/annotated/all.vcf.gz",
        # "results/qc/multiqc.html",
        # "results/plots/depths.svg",
        # "results/plots/allele-freqs.svg",


##### Modules #####


rule get_fastq_pe_gz:
    output:
        # the wildcard name must be accession, pointing to an SRA number
        "resources/reads/{accession}_1.fastq.gz",
        "resources/reads/{accession}_2.fastq.gz",
    log:
        "logs/fasterq-dump/{accession}.gz.log"
    params:
        extra="--skip-technical"
    threads: 6  # defaults to 6
    wrapper:
        "v9.8.0/bio/sra-tools/fasterq-dump"


# include: "rules/ref.smk"
# skipped variants (vep)

checkpoint genome_faidx:
    input:
        "resources/genome.fasta",
    output:
        "resources/genome.fasta.fai",
    log:
        "logs/genome-faidx.log",
    cache: True
    params:
        extra="",
    wrapper:
        "v8.1.1/bio/samtools/faidx"


rule intervals_from_fai:
    input:
        "resources/genome.fasta.fai",
    output:
        "resources/intervals.list",
    shell:
        "cut -f1 {input} > {output}"


rule genome_dict:
    input:
        "resources/genome.fasta",
    output:
        "resources/genome.dict",
    log:
        "logs/samtools/create_dict.log",
    conda:
        "envs/samtools.yaml"
    cache: True
    shell:
        "samtools dict {input} > {output} 2> {log} "


rule bwa_index:
    input:
        "resources/genome.fasta",
    output:
        idx=multiext("resources/genome.fasta", ".amb", ".ann", ".bwt", ".pac", ".sa"),
    log:
        "logs/bwa_index.log",
    wrapper:
        "v5.10.0/bio/bwa/index"


include: "rules/mapping.smk"


# include: "rules/calling.smk"

if "restrict-regions" in config["processing"]:

    rule compose_regions:
        input:
            config["processing"]["restrict-regions"],
        output:
            "results/called/{contig}.regions.bed",
        conda:
            "envs/bedops.yaml"
        shell:
            "bedextract {wildcards.contig} {input} > {output}"


rule call_variants:
    input:
        bam=get_sample_bams_dedup,
        bai=get_sample_bai_dedup,
        ref="resources/genome.fasta",
        idx="resources/genome.dict",
        # known="resources/variation.noiupac.vcf.gz",
        # tbi="resources/variation.noiupac.vcf.gz.tbi",
    output:
        gvcf=protected("results/called/{sample}.g.vcf.gz"),
    log:
        "logs/gatk/haplotypecaller/{sample}.log",
    params: # Some need to be moved to config
        extra="-G StandardAnnotation -G AS_StandardAnnotation -G StandardHCAnnotation " +
              config["params"]["gatk"]["HaplotypeCaller"] +
              " -sample-name {sample}"       
    threads: 4
    resources:
        mem_mb=1024,
    wrapper:
        "v7.6.0/bio/gatk/haplotypecaller"


rule genomics_db_import:
    input:
        gvcfs=expand(
            "results/called/{sample}.g.vcf.gz", sample=samples.index
        ),
        interval_list="resources/intervals.list",
    output:
        db=directory("results/genomicsdb"),
    log:
        "logs/gatk/genomicsdbimport.log",
    params:
        intervals=lambda w, input: input.interval_list,
        db_action="create",  # optional
        extra="",  # optional
        java_opts="",  # optional
    threads: 2
    resources:
        mem_mb=lambda wildcards, input: max([input.size_mb * 1.6, 200]),
    wrapper:
        "v7.6.0/bio/gatk/genomicsdbimport"


#####################################
# Genotype the GVCFs
#####################################

rule genotype_gvcfs:
    input:
        genomicsdb="results/genomicsdb",
        # gvcf="calls/all.g.vcf",  # combined gvcf over multiple samples
        # N.B. gvcf or genomicsdb must be specified
        # in the latter case, this is a GenomicsDB data store
        ref="resources/genome.fasta",
    output:
        vcf="results/genotyped/all.vcf.gz",
    log:
        "logs/gatk/genotypegvcfs.log"
    params:
        extra="",  # optional
        java_opts="", # optional
    resources:
        mem_mb=1024
    wrapper:
        "v7.6.0/bio/gatk/genotypegvcfs"


# include: "rules/filtering.smk"

rule select_calls:
    input:
        ref="resources/genome.fasta",
        vcf="results/genotyped/all.vcf.gz",
    output:
        vcf=temp("results/filtered/all.{vartype}.raw.vcf.gz"),
    params:
        extra=get_vartype_arg,
        # --restrict-alleles-to BIALLELIC --create-output-variant-index false
    log:
        "logs/gatk/selectvariants/{vartype}.log",
    wrapper:
        "v7.6.0/bio/gatk/selectvariants"


rule filter_calls:
    input:
        ref="resources/genome.fasta",
        vcf="results/filtered/all.{vartype}.raw.vcf.gz",
    output:
        vcf=temp("results/filtered/all.{vartype}.hardfiltered.vcf.gz"),
    params:
        filters=get_filter,
        extra="",  # optional arguments; could add --genotype-filter-expression 'GQ < 50.0' --genotype-filter-name "genotype_filters" --set-filtered-genotype-to-no-call
    log:
        "logs/gatk/variantfiltration/{vartype}.log",
    wrapper:
        "v7.6.0/bio/gatk/variantfiltration"


rule select_pass_calls:
    input:
        vcf="results/filtered/all.{vartype}.hardfiltered.vcf.gz",
        ref="resources/genome.fasta",
    output:
        vcf="results/filtered/all.{vartype}.selected.vcf.gz",
    log:
        "logs/gatk/select-pass/{vartype}.log",
    params:
        extra="--exclude-filtered",  # optional filter arguments, see GATK docs
        java_opts="",  # optional
    resources:
        mem_mb=1024,
    wrapper:
        "v7.6.0/bio/gatk/selectvariants"


# Based on best practices we could add Filter Variants by Variant (Quality Score) Recalibration
#  Tools involved: VariantRecalibrator, ApplyVQSB
#  //Need to adjust this part//
# rule recalibrate_calls:
#     input:
#         vcf="results/filtered/all.{vartype}.selected.vcf.gz"
#     output:
#         vcf=temp("results/filtered/all.{vartype}.recal.vcf.gz"),
#     params:
#         extra=config["params"]["gatk"]["VariantRecalibrator"],
#     log:
#         "logs/gatk/variantrecalibrator/{vartype}.log",
#     wrapper:
#         "v7.6.0/bio/gatk/variantrecalibrator"
#
#
# rule apply_vqsr:
#     input:
#         vcf="results/filtered/all.{vartype}.recal.vcf.gz",
#         recal="snps.recal",
#         tranches="snps.tranches",
#         ref="resources/genome.fasta",
#     output:
#         vcf="results/filtered/all.{vartype}.recalibrated.vcf.gz",
#     log:
#         "logs/gatk/applyvqsr.log",
#     params:
#         mode="SNP",  # set mode, must be either SNP, INDEL or BOTH
#         extra="",  # optional
#     resources:
#         mem_mb=1024,
#     wrapper:
#         "v7.6.0/bio/gatk/applyvqsr"


# include: "rules/stats.smk"
include: "rules/qc.smk"
# include: "rules/annotation.smk"


# filter before extracting FASTA
rule bcf_filter_o_vcf_gz:
    input:
        "results/filtered/all.snvs.selected.vcf.gz",
    output:
        temp("results/msa/all.snvs.filtered.vcf.gz"),
    log:
        "logs/bcftools/filter-msa.log",
    params:
        filter="--SnpGap 3 -e 'QUAL < 1000 || AF=1 || INFO/AF < 0.05 || F_MISSING > 0'",
        extra="",
    wrapper:
        "v8.1.1/bio/bcftools/filter"


rule msa_ref_fasta:
    input:
        "results/msa/all.snvs.filtered.vcf.gz",
    output:
        temp("results/msa/ref.fasta"),
    conda:
        "envs/variant.yaml",
    log:
        "logs/bcftools/filter-msa-ref.log",
    shell:
        """
        printf ">REF\n%s\n" \
        $(bcftools query -f '%REF' {input} | tr -d '\n') > {output} 2> {log}
        """


rule msa_sample_fasta:
    input:
        "results/msa/all.snvs.filtered.vcf.gz",
    output:
        temp("results/msa/{sample}.fasta"),
    conda:
        "envs/variant.yaml",
    log:
        "logs/bcftools/filter-msa-{sample}.log",
    shell:
        """
        printf ">{wildcards.sample}\n%s\n" \
        $(bcftools query -s {wildcards.sample} -f '[%IUPACGT]' {input} | tr -d '\n') > {output} 2> {log}
        """


rule concat_fasta:
    input:
        ref="results/msa/ref.fasta",
        samples=expand("results/msa/{sample}.fasta", sample=samples.index)
    output:
        "results/msa/snvs.fasta"
    shell:
        """
        cat {input.ref} {input.samples} > {output}
        """


# Phylogeny

rule fasttree:
    input:
        alignment="results/msa/{alnname}.fasta",  # Input alignment file
    output:
        tree="results/phylogeny/fasttree-{alnname}.nwk",  # Output tree file
    log:
        "logs/fasttree/fasttree-{alnname}.log",
    params:
        extra="-gtr -gamma -nt",  # Additional arguments
    wrapper:
        "v7.3.0/bio/fasttree"


# Assembly

# rule spades_simple:
#     input:
#         r1="results/trimmed/{sample}-1.1.fastq.gz", # r1=temp("results/trimmed/{sample}-{unit}.1.fastq.gz"),
#         r2="results/trimmed/{sample}-1.2.fastq.gz", # r2=temp("results/trimmed/{sample}-{unit}.2.fastq.gz"),
#     output:
#         contigs="spades/{sample}/contigs.fasta",
#         scaffolds="spades/{sample}/scaffolds.fasta",
#         fastg="spades/{sample}/assembly_graph.fastg"
#     log:
#         "logs/spades/{sample}.log"
#     conda:
#         "envs/spades.yaml"
#     params:
#         extra="--careful"
#     threads:
#         workflow.cores
#     shell:
#         """
#         spades.py -1 {input.r1} -2 {input.r2} -t {threads} \
#         -o spades/{wildcards.sample} {params} 2> {log}
#         """


rule spades_pe:
    """
    Assembles reads using SPAdes (works only for single lib at the moment)
    """
    input:
        reads=lambda wildcards: [item for sublist in [["results/trimmed/{sample}-{unit}.1.fastq.gz".format(sample=wildcards.sample, unit=u),
                                     "results/trimmed/{sample}-{unit}.2.fastq.gz".format(sample=wildcards.sample, unit=u)]
                                      for u in units.loc[wildcards.sample].unit] for item in sublist]
    output:
        contigs="results/spades/{sample}/contigs.fasta",
        scaffolds="results/spades/{sample}/scaffolds.fasta",
        fastg="results/spades/{sample}/assembly_graph.fastg"
        # "results/assemblies/{sample}/contigs.fasta"
    log:
        "logs/spades/{sample}.log",
    conda:
        "envs/spades.yaml" 
    params:
        input_param=lambda wildcards: " ".join(["--pe{unit}-1 results/trimmed/{sample}-{unit}.1.fastq.gz --pe{unit}-2 results/trimmed/{sample}-{unit}.2.fastq.gz".format(
            sample=wildcards.sample, unit=u) for u in units.loc[wildcards.sample].unit]),
        extra="--careful"
    threads:
        16
    shell:
        "spades.py {params} -t {threads} -o assemblies/{wildcards.sample}"


rule get_organelles:
    input:
        fastg="results/spades/{sample}/assembly_graph.fastg",
    output:
        mt="results/get_organelles/{sample}/fungus_mt.complete.graph1.1.path_sequence.fasta",
        nr="results/get_organelles/{sample}/fungus_nr.complete.graph1.1.path_sequence.fasta",
        csv="results/get_organelles/{sample}/slimmed_assembly_graph.csv",
    log:
        "logs/get_organelles/{sample}.log",
    conda:
        "envs/get_organelles.yaml"
    params:
        targets="fungus_nr,fungus_mt"
    shell:
        """
        get_organelle_from_assembly.py -F {params.targets} -g {input.fastg} -o results/get_organelles/{wildcards.sample} 2> {log}
        """


rule filter_spades_contigs:
    input:
        contigs="results/spades/{sample}/contigs.fasta",
        paths="resutlts/spades/{sample}/contigs.paths",
        csv="results/get_organelles/{sample}/slimmed_assembly_graph.csv",
    output:
        "results/get_organelles/{sample}/filtered-contigs.fasta",
    log:
        "logs/filter_spades/{sample}.log",
    # conda:
    #     "envs/filter_spades.yaml"
    shell:
        """
        perl filter_spades_contigs.pl --contigs {input.contigs} --paths {input.paths} --csv {input.csv} > {output} 2> {log}
        """